## Meta Configs for Essai
name: flan-t5-ul2
description: T5 model with instructive prompts in Flan style
model_argument: NI
dataset_argument: Flan
training_argument: NI
peft: True
## Huggingface Configs
run_name: flan-t5-ul2-experiment-eduqog-pos
deepspeed: essai/ds_configs/stage3_ul2.config
do_train: True
do_predict: True
do_eval: True
predict_with_generate: True
model_name_or_path: google/flan-ul2
max_source_length: 1024
max_target_length: 128
generation_max_length: 128
data_file: "essai/dataset/flan/flan_dataset.py"
data_dir: data/eduqg/splits/defaults
task_dir: data/eduqg/flan_tasks
resume_from_checkpoint: output/eduqg_flan_t5_ul2_few_shots_question_options/checkpoint-300/
output_dir: output/eduqg_flan_t5_ul2_few_shots_question_options
overwrite_output_dir: True
add_few_shots: True
num_shots: 2
overwrite_cache: True
per_device_train_batch_size: 1
per_device_eval_batch_size: 2
gradient_accumulation_steps: 3
learning_rate: 1.0e-4
num_train_epochs: 2
lr_scheduler_type: constant
warmup_steps: 100
logging_strategy: steps
logging_steps: 1
evaluation_strategy: "steps"
eval_steps: 601
save_strategy: steps
save_steps: 300
bf16: True